// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1:string,arg2:Array<any>):Promise<string>;

export function SaveResult(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
