// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2) {
  return window['go']['main']['App']['Convert'](arg1, arg2);
}

export function SaveResult(arg1) {
  return window['go']['main']['App']['SaveResult'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
